spring:
  redis:
    host: '127.0.0.1'
    port: 6379
  kafka:
    consumer:
      bootstrap-servers: localhost:9092
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      group-id: 'audit-action'
    topic:
      audit: 'audit'

